In [1]:
#let's import the necessary libraries and load the data from the fileimport pandas as pd
import numpy as np

data = pd.read_excel("C:\\Users\\This PC\\Downloads\\investment decisions.xlsx", index_col=0)

In [2]:
#We can check the first few rows of the data
print(data.head())

            EQ_Australia      EQ_US     EQ_UK  EQ_Japan  EQ_China  EQ_India  \
Date
2021-10-01      6.350853  13.752778  8.032026  5.581721  7.028903  3.978308
2021-09-30      6.480415  13.596517  8.099871  5.704882  7.028903  3.998465
2021-09-29      6.360685  13.759511  8.118093  5.727666  7.007622  4.020220
2021-09-28      6.429977  13.736671  8.026660  5.809246  7.023787  4.029254
2021-09-27      6.525969  14.021554  8.067007  5.825878  7.011001  4.054036

            EQ_Brazil  FI_Australia_10  FI_US_10  FI_UK_10  FI_Japan_10  \
Date
2021-10-01   1.758624         2.776433  2.534220  3.186890     2.848282
2021-09-30   1.729170         2.778488  2.519853  3.181045     2.843023
2021-09-29   1.731605         2.776881  2.516955  3.189750     2.844090
2021-09-28   1.716734         2.783776  2.517689  3.188769     2.841288
2021-09-27   1.771138         2.797956  2.529713  3.200409     2.846764

            FI_China_5  FI_India_5  FX_Japan    FX_UK  FX_Australia  \
Date
2021-10-01    1.221621    1.231593   65.2674  90.3634      180.9009
2021-09-30    1.221602    1.231808   65.0104  89.6972      179.4837
2021-09-29    1.222120    1.232408   64.7148  89.4573      178.6635
2021-09-28    1.221186    1.231072   65.0233  90.1572      179.9580
2021-09-27    1.220493    1.230465   65.2699  91.3303      181.3025

            FX_Brazil  FX_India
Date
2021-10-01   175.4642  196.7232
2021-09-30   172.8856  196.3940
2021-09-29   173.7361  196.6016
2021-09-28   173.2247  196.8327
2021-09-27   174.4131  197.3654

In [3]:
returns = data.pct_change().dropna()
data

,EQ_Australia,EQ_US,EQ_UK,EQ_Japan,EQ_China,EQ_India,EQ_Brazil,FI_Australia_10,FI_US_10,FI_UK_10,FI_Japan_10,FI_China_5,FI_India_5,FX_Japan,FX_UK,FX_Australia,FX_Brazil,FX_India
Date,,,,,,,,,,,,,,,,,,
2021-10-01,6.350853,13.752778,8.032026,5.581721,7.028903,3.978308,1.758624,2.776433,2.534220,3.186890,2.848282,1.221621,1.231593,65.2674,90.3634,180.9009,175.4642,196.7232
2021-09-30,6.480415,13.596517,8.099871,5.704882,7.028903,3.998465,1.729170,2.778488,2.519853,3.181045,2.843023,1.221602,1.231808,65.0104,89.6972,179.4837,172.8856,196.3940
2021-09-29,6.360685,13.759511,8.118093,5.727666,7.007622,4.020220,1.731605,2.776881,2.516955,3.189750,2.844090,1.222120,1.232408,64.7148,89.4573,178.6635,173.7361,196.6016
2021-09-28,6.429977,13.736671,8.026660,5.809246,7.023787,4.029254,1.716734,2.783776,2.517689,3.188769,2.841288,1.221186,1.231072,65.0233,90.1572,179.9580,173.2247,196.8327
2021-09-27,6.525969,14.021554,8.067007,5.825878,7.011001,4.054036,1.771138,2.797956,2.529713,3.200409,2.846764,1.220493,1.230465,65.2699,91.3303,181.3025,174.4131,197.3654
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000-01-07,1.937886,4.590604,5.958154,3.087636,2.859320,1.108332,2.272210,1.628957,1.264395,1.651871,1.743671,NaN,NaN,102.3818,98.6086,106.5442,75.2305,104.8932
2000-01-06,1.922860,4.470560,5.906781,3.108087,2.755680,1.111716,2.244046,1.625186,1.259661,1.645123,1.748056,NaN,NaN,102.4048,99.0779,106.4974,74.6106,104.9000
2000-01-05,1.935719,4.466439,5.989454,3.189694,2.626467,1.097142,2.263323,1.647736,1.255349,1.645884,1.746608,NaN,NaN,103.8194,99.0173,106.7268,74.6820,105.0049
2000-01-04,1.984244,4.458515,6.110023,3.316444,2.634175,1.127048,2.208441,1.647157,1.265432,1.657320,1.742237,NaN,NaN,104.5480,98.6676,106.7774,74.1681,104.9538
2000-01-03,2.000078,4.637216,6.353778,3.325608,2.547455,1.095459,2.358856,1.647788,1.259114,1.679575,1.751592,NaN,NaN,106.0634,98.3420,107.3971,75.4395,104.8794

In [4]:
#we can calculate the daily returns of each asset 
mu = returns.mean()
sigma = returns.std()

In [5]:
#we can calculate the daily returns of each asset 
rf = 0.02 # risk-free rate
sharpe_ratio = (mu - rf) / sigma

In [6]:
#We can then select the top 16 assets with the highest Sharpe ratio
selected_assets = sharpe_ratio.nlargest(16).index

In [7]:
#we can calculate the expected return and volatility of a portfolio that invests equally in these 16 assets:
weights = np.ones(len(selected_assets)) / len(selected_assets)
portfolio_return = np.sum(mu[selected_assets] * weights)
portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(returns[selected_assets].cov(), weights)))

In [8]:
#We can print the selected assets and the portfolio statistics:
print("Selected assets:", selected_assets)
print("Expected portfolio return:", portfolio_return)
print("Portfolio volatility:", portfolio_volatility)

Selected assets: Index(['EQ_Brazil', 'EQ_China', 'EQ_India', 'EQ_Japan', 'EQ_US', 'EQ_UK',
       'FX_Brazil', 'EQ_Australia', 'FX_Australia', 'FX_Japan', 'FX_UK',
       'FI_Australia_10', 'FI_US_10', 'FX_India', 'FI_UK_10', 'FI_China_5'],
      dtype='object')
Expected portfolio return: -4.271358984655762e-05
Portfolio volatility: 0.004180794834616924

In [ ]:
import matplotlib.pyplot as plt

# Plot the selected assets
plt.scatter(sigma[selected_assets], mu[selected_assets])

# Add labels for each point
for i, asset in enumerate(selected_assets):
    plt.annotate(asset, (sigma[asset], mu[asset]))

# Add the portfolio point
plt.scatter(portfolio_volatility, portfolio_return, color='red')

# Add labels and title
plt.xlabel('Volatility')
plt.ylabel('Expected Return')
plt.title('Efficient Frontier')

plt.show()